2011-04-20 02:19 UTC+0200 Viktor Szakats (harbour.01 syenar.hu)   * contrib/hbunix/hbunix.hbp   * contrib/hbcurl/hbcurl.hbm   * contrib/hbnetio/hbnetio.hbp   * contrib/hbnetio/hbnetio.hbx   * contrib/gtwvg/gtwvg.hbp   * contrib/hbwin/hbwin.hbp   * contrib/hbsqlit3/hbsqlit3.hbp   * contrib/hbexpat/hbexpat.hbp     + Enabled -std=c89 option when building with any gcc compiler.       (TOFIX: now GTWVG breaks with error)
      I mean this as an experiment which I'd like to extend
      gradually to whole Harbour as it seems a good way to
      ensure the code being truly ANSI C as we claim it. It 
      can certainly avoid a few unnecessary rounds with 
      committed code problems.

      Now that there are multiple ANSI C standards we may
      want to discuss which level we want to stick with
      (C89/C90, C99, C1X) until then let's assume C89 even though
      not all of Harbour code complies ATM. F.e.:
         ../../../hbprintf.c:543:4: warning: implicit declaration of function 'modfl'
         ../../../hbprintf.c:1146:25: warning: implicit declaration of function 'isfinite'

  * contrib/hbqt/qtgui/hbqt_hbqsyntaxhighlighter.cpp
  * contrib/hbqt/qtgui/hbqt_hbqplaintextedit.cpp
  * contrib/hbqt/qtgui/hbqt_hbqgraphicsscene.cpp
  * contrib/hbqt/qtgui/hbqt_hbqgraphicsitem.cpp
  * contrib/hbqt/qtcore/hbqt_pointer.cpp
  * contrib/hbqt/qtcore/hbqt_hbqslots.cpp
    ! Converted C++ style comments to ANSI C.
      Even though it's C++ code it's good to stick with one
      comment style (ANSI C) accross Harbour to avoid getting wrong customs.
      Pls stick to it.