2014-01-04 23:52 UTC+0100 Viktor Szakáts (vszakats users.noreply.github.com)   - contrib/gtwvg/tests/_cuigdlg.prg   * contrib/gtwvg/tests/*.prg   - extras/gtwvw/tests/_wvwmous.prg   * extras/gtwvw/tests/*.prg   * utils/hbtest/*.prg     % using STATIC PROC/FUNC where possible     % deleted unused functions     % merged source from few separate files     * other cleanups (using codeblocks, std extension)
  * doc/en/terminal.txt
    ! minor fix to prev

  ; TOFIX: wrong .c code generated in this scenario, when compiling a.prg:
           --- a.prg
           PROCEDURE Main()
              b()
              RETURN
           SET PROCEDURE TO "p.prg"
           ---

           --- p.prg
           STATIC PROCEDURE b()
              RETURN
           ---

           when .c code is compiled mingw 4.8 output is this:
           ---
           In file included from ../include/hbvmpub.h:52:0,
                            from a.c:7:
           include/hbdefs.h:1596:51: error: static declaration of 'HB_FUN_B' follows non-static declaration
            #define HB_FUNC_STATIC( funcname ) static HARBOUR HB_FUN_##funcname ( void )
                                                              ^
           a.c:16:1: note: in expansion of macro 'HB_FUNC_STATIC'
            HB_FUNC_STATIC( B );
            ^
           include/hbdefs.h:1595:78: note: previous declaration of 'HB_FUN_B' was here
            #define HB_FUNC_EXTERN( funcname ) HB_EXTERN_C_ HB_EXTERN_ HARBOUR HB_EXPORT HB_FUN_##funcname ( void )
                                                                                         ^
           a.c:14:1: note: in expansion of macro 'HB_FUNC_EXTERN'
            HB_FUNC_EXTERN( B );
            ^
           ---