2009-10-22 20:31 UTC+0200 Viktor Szakats (harbour.01 syenar.hu)   * contrib/hbqt/Makefile   * contrib/hbqt/qtgui/Makefile   * contrib/hbqt/qtwebkit/Makefile   * contrib/hbqt/qtcore/Makefile   * contrib/hbqt/qtnetwork/Makefile   * contrib/hbqt/hbqts.hbc     ! Minor cleanups and fixes after recent restructuring.         Nice job Pritpal.
    ; TODO: Since now QT detection .mk code will be replicated 
            in 10 places, this will have to be optimized.
    ; TOFIX: static mode.

    ; TOFIX: I'm getting a compile error, so could check the whole build run yet:
      ---
      hbqt_slots.cpp
      ../../../hbqt_slots.cpp(1787) : error C2065: 'str' : undeclared identifier
      ../../../hbqt_slots.cpp(1787) : error C2065: 'str' : undeclared identifier
      ../../../hbqt_slots.cpp(1787) : error C2070: ''unknown-type'': illegal sizeof operand
      ../../../hbqt_slots.cpp(1787) : error C2065: 'str' : undeclared identifier
      ---
    ; TOFIX: I saw these warnings in almost all tested .cpp files:
      ---
      ../../../QWebSettings.cpp(86) : warning C4100: 'Cargo' : unreferenced formal parameter
      ---

  * contrib/hbqt/generator/hbqtgen.prg
  * contrib/hbqt/generator/qt45.qtp
    ! Added missing SVN headers.

  * contrib/hbqt/hbqt.hbc
    + Minor formatting.