2009-05-20 20:02 UTC+0200 Viktor Szakats (harbour.01 syenar hu)   * utils/hbmk2/hbmk2.prg     ! Added workaround for DIRECTORY() problem under Windows.       '*.ext' input files weren't working if the actual filenames       had different casing (on Windows). Also changed the hack       to only kick in on Windows platforms, *nixes seems to work       as expected.     ; NOTE: This workaround should probably be moved to Harbour             FileFind API.
  * INSTALL
    + Added HB_INC_ODBC.

  * contrib/hbwin/tests/testole.prg
  * contrib/hbwin/legacyc.c
    * Updated to reflect OLE function name changes.

  * contrib/hbwin/legacyc.c
    + Added GETACTIVEOBJECT(), CREATEOBJECT(), OLEERROR()
      compatibility calls. All of them are simple aliases to
      new OLE function, which means there may be differences
      in behviour. Users will need to adjust them for full
      compatibility.
      However, I'd recommend changing all code to use our
      new OLE functions and classes.

  * contrib/hbwin/Makefile
  + contrib/hbwin/legacy.prg
    * Moved TOLEAUTO() compatibility class to .prg level.
      It's a stub, inheriting from WIN_OLEAUTO. I hope TOLEAUTO
      users will fill it with required compitibility methods.

  ; NOTE: Getting these warnings with bcc:
          Warning W8075 ../../axcore.c 93: Suspicious pointer conversion in function hb_ax_init
          Warning W8075 ../../axcore.c 322: Suspicious pointer conversion in function HB_FUN___AXREGISTERHANDLER

  ; NOTE: Getting these errors with msvc (default C++ mode):
          ../../axcore.c(93) : error C2440: '=' : cannot convert from 'FARPROC' to 'HRESULT (__stdcall *)(HWND,IUnknown **)'
                  This conversion requires a reinterpret_cast, a C-style cast or function-style cast
          ../../axcore.c(146) : error C2143: syntax error : missing ';' before '*'
          ../../axcore.c(146) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
          ../../axcore.c(146) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
          ../../axcore.c(175) : error C2039: 'lpVtbl' : is not a member of 'ISink'
                  ../../axcore.c(145) : see declaration of 'ISink'
          ../../axcore.c(175) : error C2227: left of '->Release' must point to class/struct/union/generic type
          ../../axcore.c(179) : error C2143: syntax error : missing ')' before 'this'
          ../../axcore.c(179) : error C2143: syntax error : missing ';' before 'this'
          ../../axcore.c(179) : error C2059: syntax error : ')'
          ../../axcore.c(180) : error C2143: syntax error : missing ';' before '{'
          ../../axcore.c(180) : error C2447: '{' : missing function header (old-style formal list?)
          [ ...snip... ]
          ../../axcore.c(198) : error C2365: 'Release' : redefinition; previous definition was 'formerly unknown identifier'
          [ ...snip... ]
          ../../axcore.c(282) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
          ../../axcore.c(282) : error C2146: syntax error : missing ';' before identifier 'ISink_Vtbl'
          ../../axcore.c(282) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
          ../../axcore.c(283) : error C2440: 'initializing' : cannot convert from 'HRESULT (__stdcall *)(IDispatch *)' to 'int'
                  There is no context in which this conversion is possible
          ../../axcore.c(284) : error C2078: too many initializers
          ../../axcore.c(322) : error C2039: 'lpVtbl' : is not a member of 'ISink'
                  ../../axcore.c(145) : see declaration of 'ISink'