2010-06-20 01:13 UTC+0200 Viktor Szakats (harbour.01 syenar.hu)   * config/win/pocc.mk   * config/win/pocc64.mk     ! Fixed pocc64 build. The build setup was broken since       about 2.0.0beta2. One year without anyone noticing.
  * src/rtl/hbsocket.c
    ! Readded once present (in old hbinet.c) ugly kludge for pocc64
      to at least be able to build binaries instead of choking on a
      missing Windows function. More in the source code.
      Affecting both 5 and 6.

  * external/zlib/Makefile
    ! Added ugly workaround to avoid quite strange pocc64 (both 5 and 6)
      error when compiling crc32 for dynamic lib:
      ---
      pocc.exe -I. -I../../../../../include -Ze -Go -MT -Tamd64-coff -Ot -DHB_LEGACY_TYPES_OFF -DUNICODE -Focrc32_dyn.obj -DHB_DYNLIB -DZLIB_DLL -c ../../../crc32.c
      ../../../crc32.c(209): error #3101: [asm] Invalid argument to 'GLOBAL'.
      ../../../crc32.c(209): error #3152: [asm] Expected ']'.
      ../../../crc32.c(209): error #3151: [asm] Syntax error.
      ../../../crc32.c(223): error #3101: [asm] Invalid argument to 'FUNCTION'.
      ../../../crc32.c(223): error #3152: [asm] Expected ']'.
      ../../../crc32.c(223): error #3151: [asm] Syntax error.
      ../../../crc32.c(223): error #3151: [asm] Syntax error.
      ---

  * external/bzip2/Makefile
    ! Disabled for pocc64 (both 5 and 6), due to this error:
      ---
      pocc.exe -I. -I../../../../../include -Ze -Go -MT -Tamd64-coff -Ot -DHB_LEGACY_TYPES_OFF -DUNICODE -Foblocksor.obj -c ../../../blocksor.c
      ../../../blocksor.c(583): error #3114: [asm] Invalid combination of opcode and operands.
      ---